modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="beescuit"
version="1.0.0"
displayName="Beescuit"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="piscot, MCreator"

[[dependencies.beescuit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



